# Generated by Django 5.2 on 2025-05-05 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=255)),
                ('uses', models.CharField(max_length=255)),
                ('preparation', models.TextField()),
                ('warnings', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='herbs.category')),
            ],
        ),
        migrations.CreateModel(
            name='HealthTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb_name', models.CharField(max_length=100)),
                ('perceived_effectiveness', models.CharField(choices=[('very_ineffective', 'Very ineffective'), ('ineffective', 'Ineffective'), ('neutral', 'Neutral'), ('effective', 'Effective'), ('very_effective', 'Very effective')], max_length=30)),
                ('side_effects', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.herb')),
            ],
        ),
    ]
