# Generated by Django 5.2 on 2025-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='herb',
            name='uses',
            field=models.CharField(max_length=255),
        ),
    ]
