# Generated by Django 5.2 on 2025-05-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0002_alter_herb_image_url_alter_herb_uses'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('perceived_effectiveness', models.CharField(choices=[('very_ineffective', 'Very ineffective'), ('ineffective', 'Ineffective'), ('neutral', 'Neutral'), ('effective', 'Effective'), ('very_effective', 'Very effective')], max_length=30)),
                ('side_effects', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
