# Generated by Django 5.2 on 2025-05-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0003_healthtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtracker',
            name='used_for',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
