# Generated by Django 5.2 on 2025-05-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0004_healthtracker_used_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthtracker',
            name='used_for',
        ),
    ]
