# Generated by Django 5.2 on 2025-05-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0005_remove_healthtracker_used_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthtracker',
            old_name='name',
            new_name='herb_name',
        ),
        migrations.AddField(
            model_name='healthtracker',
            name='herb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='herbs.herb'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthtracker',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
