# Generated by Django 5.2 on 2025-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0006_rename_name_healthtracker_herb_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
