# Generated by Django 5.2 on 2025-05-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0007_alter_herb_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image_url',
            field=models.URLField(max_length=255),
        ),
    ]
